export const HOME_PAGE = 'home'
export const LOGIN_PAGE = 'login'
export const ABOUT_PAGE = 'about'
export const USERS_PAGE = 'users'
export const USER_CREATE_PAGE = 'user-create'
export const USER_UPDATE_PAGE = 'user-update'
